### ISSUE TITLE
Nan Loss during training MNIST dataset

### ISSUE THREAD

**Issue by mmderakhshani** [brjathu/iTAML#10]
Hi. First of all, I have to appreciate regarding your great implementation. 

During training on MNIST dataset using the following command, I found nan: 
![Screenshot (395)](https://user-images.githubusercontent.com/16706043/86520020-9da14e00-be40-11ea-803a-fbce4bbab6ac.png)

Could you please explain to me am I doing something wrong? I just ran following command:
```
python train_mnist.py 0
```

**Comment by brjathu** [comment]
It seems a problem in the code. I will check on that, meanwhile, You can stop after getting NAN, 
and run python train_mnist.py 3
it will start from session 3 and after the restart, it seems working fine.

**Comment by mmderakhshani** [comment]
Thanks for the reply and thanks for the suggestion.
