### ISSUE TITLE
What is the difference between two output of model? -->outputs2, outputs = model(inputs)

### ISSUE THREAD

**Issue by guanlinting** [brjathu/iTAML#14]
Thanks for open source your great work, I'm confused when read the source code, the model has two same output  x1 and x2.

>         x1 = self.fc(x)
>         x2 = self.fc(x)
>         return x1, x2

In Learner,  some time use x1, some times use x2 or both, like 

> outputs2, outputs = model(inputs) 
> outputs2, _ = model(inputs)  
> _, outputs = meta_model(inputs)

What is the purpose of such a design?

**Comment by brjathu** [comment]
Hi, sorry for the confusion. It’s was added to keep the api same across all the modules. It’s the same thing as single pass, and it should be (to reduce computation). Algorithmic wise it doesn’t change anything at all. We will polish the code to reduce the confusion. Thanks.
