### ISSUE TITLE
Running without CUDA

### ISSUE THREAD

**Issue by nlrahimi** [brjathu/iTAML#16]
Thanks for the code and the amazing job you did to share the requirements and dependencies to facilitate running the model for community. I was able to run the code on a GPU-enabled Ubuntu 18.04. but could not run it without using GPU. I was wondering if we can run the model without using GPU.

Thanks

**Comment by brjathu** [comment]
Thank you very much :) 
Actually you can run but there are many parts in the code that assume GPU is available. You can find an replace .cuda() in the code to .cpu() everywhere. It should work, if it doesn’t please let us know.

**Comment by nlrahimi** [comment]
Great! I will modify it as suggested.

Bests
