### ISSUE TITLE
AttributeError: type object 'args' has no attribute 'overflow'

### ISSUE THREAD

**Issue by Kelly368** [brjathu/iTAML#2]
Hello,someone.
When i run python3 train_cifar.py 0 ,it raises an error:’AttributeError: type object 'args' has no attribute 'overflow'
Thanks someone for helping me.

**Comment by brjathu** [comment]
Hi @Kelly368, I have fixed the dataloaded, which previously used overflow argument. Let me if you have any questions.

https://github.com/brjathu/iTAML/commit/e8ec1e7f1c988cdb8f0d9045fe5ec7fd7acdc7e0

**Comment by Kelly368** [comment]
It worked!Thank you so much!
