### ISSUE TITLE
something wrong happends in training cifar10

### ISSUE THREAD

**Issue by wangjl1993** [brjathu/iTAML#3]
in incremental_dataloader.py:

class iCIFAR10(DataHandler):
    base_dataset = datasets.cifar.CIFAR10
    train_transforms = [
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ColorJitter(brightness=63 / 255),
        transforms.ToTensor(),
    ]
    common_transforms = [
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
    ]

train_transforms has no Normalize function, this will get unworkable when testing.

**Comment by brjathu** [comment]
Hi, I have updated the code, however we haven't done any experiments on CIFAR10, on the paper. It was added for the completeness of the data loader.

**Comment by wangjl1993** [comment]
> Hi, I have updated the code, however we haven't done any experiments on CIFAR10, on the paper. It was added for the completeness of the data loader.

Hi~ yes, I could get the same acc on cifar100, it is just a friendly reminder.  Both your idea and code are really cool! thx~~

**Comment by brjathu** [comment]
Thank you very much.
