### ISSUE TITLE
Where to check task accuracy and class accuracy?

### ISSUE THREAD

**Issue by xialeiliu** [brjathu/iTAML#4]
Fig 7 shows interesting performance of both task accuracy and class accuracy, I am wondering where to check those numbers. And where to decide the size of data continuum? Sorry I couldn't find corresponding part in the code. I might missed something. Thanks.

**Comment by brjathu** [comment]
Hi, the testing part of the code is the plot_cifar_10.ipynb file, function `get_mata_score()`.

**Comment by xialeiliu** [comment]
Oh, I see. Thanks,
