### ISSUE TITLE
sys.argv[1] is out of range

### ISSUE THREAD

**Issue by nlrahimi** [brjathu/iTAML#6]
Hello,

Thanks for the amazing paper and your contribution to share your code.

I have an issue and would appreciate your help to solve it:
When running 'train_cifar' code, I face _"out of index error"_ for line 97:
start_sess=int(sys.argv[1])
when checking len(sys.argv) = 1, that is why sys.argv[1] is out of index
I changed the code in that same line to to sys.arg[0] and faced another error:
_"invalid literal for int() with base 10: '/codepath/train_cifar.py"_

I have been stumped in solving this error and would appreciate your suggestion.
I am using Ubuntu 18.04 - nvidia gpu
Thanks you

**Comment by brjathu** [comment]
Hi @nlrahimi, Thanks for your appreciation. 

`python filename.py 4` here filename.py is sys.argv[0] and, 4 is sys.argv[1].

sys.argv[1] takes a single integer and use it as the session id. or you could simply replace line 97 `start_sess = int(sys.argv[1])` with `start_sess = 0`.

if you could share the command you were using, I can comment on further.

**Comment by nlrahimi** [comment]
Thank you brjathu
the problem was solved.

All the bests
